### ISSUE TITLE
[BUG] Clicknon TODAY in Energy Period Selector Plus nothing happens

### ISSUE THREAD

**Issue by Phoenix-DH** [flixlix/energy-flow-card-plus#84]
**Describe the bug**
When selecting a week or something on the date seöwctor, clicking on today, nothing happens

**To Reproduce**
1. Go to week view
2. Click on today
3. See error

**Expected behavior**
Come back to current day.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS 17.0.1
 - Browser: all
 - Version all

**Smartphone (please complete the following information):**
 - Device: iPhone13
 - OS: iOS 17.0.1

**Additional context**

**Please make sure all of this applies and check the checkboxes, by writing "X" inside of them.**

- [X] I understand that this is a channel for reporting bugs, not a support forum (If you need help configuring the card, go to: [Discussions](https://github.com/flixlix/energy-flow-card-plus/discussions)).

- [X] I have the latest version of the card installed.

- [X] I have cleared my browser cache **after** installing, updating and configuring the card.

**Comment by flixlix** [comment]
This is expected behaviour. It is the same behaviour as in the builtin period selector.

Depending on the current view selected (Day, Week, Month or Year) clicking the `TODAY` button will got to the newest dataset available. Meaning, when you have Week selected and go to the previous week, clicking the `TODAY` button will come back to the current week.

I get that this doesn't make much sense because of the naming, but then again, you can change the `TODAY` button type to an icon.

**Comment by Phoenix-DH** [comment]
Oh okay, thanks for the explanation.
Was not aware of that.
